server:
  tcp_addr: "tcp://0.0.0.0:8080"
  ws_addr: "0.0.0.0:8083"
  http_addr: "0.0.0.0:8082"
  request_pool_size: 20000
  message_pool_size: 40000
  request_timeout: "10s"
  max_idle: "120s"
  log_detail: true
  cert_file: "" # Path to your SSL certificate (e.g., ./certs/server.crt)
  key_file: ""  # Path to your SSL key (e.g., ./certs/server.key)

redis:
  addr: "localhost:6379"
  password: ""
  db: 0
mysql:
  addr: "localhost:3306"
  user: "root"
  password: "my-secret-pw"
  db_name: "btaskee_quiz"

token:
  secret_key: "this-is-a-very-secret-key-that-must-be-at-least-32-chars"
  access_token_duration: "24h"
  refresh_token_duration: "168h"
